name: PR Lint

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  actionlint:
    name: Action Lint
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Run actionlint
      uses: raven-actions/actionlint@v1

  check-branch:
    name: Check Branch Naming
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Check branch name
      uses: deepakputhraya/action-branch-name@master
      with:
        regex: '^(feature|fix|docs|style|refactor|test|chore)\/[a-z0-9-]+$'
        allowed_prefixes: 'feature,fix,docs,style,refactor,test,chore'
        min_length: 3
        max_length: 50
